name: Client
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - name: Run tests
        run: npx nx run client:test --codeCoverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: client
